// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWi0KXVPGauHmj_bNOGiSllDjtMBuyWQ',
    appId: '1:212692119533:web:078d88b8bb58f151e801e4',
    messagingSenderId: '212692119533',
    projectId: 'projet-fin-etude-69d11',
    authDomain: 'projet-fin-etude-69d11.firebaseapp.com',
    storageBucket: 'projet-fin-etude-69d11.firebasestorage.app',
    measurementId: 'G-77SGDV1HQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwoN0WeFcD6EpC9wY9gZbLBI_GGIqE7rE',
    appId: '1:212692119533:android:2a024fe961ce4c92e801e4',
    messagingSenderId: '212692119533',
    projectId: 'projet-fin-etude-69d11',
    storageBucket: 'projet-fin-etude-69d11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPDJyiszfqk3lE5sR6nOwOPb_bTLQpZuw',
    appId: '1:212692119533:ios:9e988ca7d49b4322e801e4',
    messagingSenderId: '212692119533',
    projectId: 'projet-fin-etude-69d11',
    storageBucket: 'projet-fin-etude-69d11.firebasestorage.app',
    iosBundleId: 'com.example.projetFinEtude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPDJyiszfqk3lE5sR6nOwOPb_bTLQpZuw',
    appId: '1:212692119533:ios:9e988ca7d49b4322e801e4',
    messagingSenderId: '212692119533',
    projectId: 'projet-fin-etude-69d11',
    storageBucket: 'projet-fin-etude-69d11.firebasestorage.app',
    iosBundleId: 'com.example.projetFinEtude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWi0KXVPGauHmj_bNOGiSllDjtMBuyWQ',
    appId: '1:212692119533:web:6dcd35349388fc7be801e4',
    messagingSenderId: '212692119533',
    projectId: 'projet-fin-etude-69d11',
    authDomain: 'projet-fin-etude-69d11.firebaseapp.com',
    storageBucket: 'projet-fin-etude-69d11.firebasestorage.app',
    measurementId: 'G-9RKMXXV9LC',
  );
}
